hazhongkeji/hazhongkeji/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mdeditor/', include('mdeditor.urls')),
    url(r'^hazhong/', include('hazhongsite.urls')),
    url(r'^zhizhu/', include('zhizhu_proxy.urls')),
    url(r'^hongchang/', include('hongchang.urls')),
    url(r'^xiaohua/', include('xiaohua_spider.urls')),
    url(r'^auth/', include('myauth.urls',namespace='myauth')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^xinhongguang/', include('allauth.urls')),


]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hazhongkeji/myauth/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from myauth import views

urlpatterns = [
    url(r'^weixin$',views.WeixinAuth.as_view(),name='weixinauth'),
]

hazhongkeji/zhizhu_proxy/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from zhizhu_proxy import views

urlpatterns = [
    url(r'^index$',views.zhizhu_index.as_view(),name='index'),
    url(r'^login$',views.Login.as_view(),name='login'),
    # url(r'^login$',views.login),
    # url(r'^shuju/page(?P<num>[0-9]+)/$',views.Shuju.as_view()),
    url(r'^shuju/$',views.Shuju.as_view()),

]

hazhongkeji/zhizhu_proxy/models.py
from django.db import models



class UserInfo(models.Model):

    username = models.CharField(max_length=32, verbose_name='姓名',null=True)
    phone = models.CharField(max_length=32, verbose_name='联系方式', unique=True)
    number = models.CharField(max_length=32, verbose_name='网吧代码',default='003')
    city = models.CharField(choices=None,max_length=32, null=True, verbose_name='城区')
    wb = models.CharField(max_length=32, null=True, verbose_name='网吧')

    class Meta:
        verbose_name = '报名信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username

class City(models.Model):
    city = models.CharField(max_length=32, verbose_name='城区',null=True)

    class Meta:
        verbose_name = '城区名称'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.city


class Wangba(models.Model):
    wb = models.CharField(max_length=32,verbose_name='网吧名称',null=True)
    wb_for = models.ForeignKey(to=City, max_length=32, verbose_name='属于哪个区',null=True,)

    class Meta:
        verbose_name = '网吧名称'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.wb

hazhongkeji/zhizhu_proxy/forms.py
# -*- coding: utf-8 -*-
from django import forms
from . import models


class Myforms(forms.Form):
    cc = models.City.objects.all()
    username = forms.CharField(
        max_length=32,
        error_messages={
            'required': '姓名不能为空',
            'invalid': '格式错误',
        },
    )
    phone = forms.CharField(
        max_length=11,
        min_length=11,
        error_messages={
            'required': '电话号不能为空',
            'invalid': '格式错误',
            'max_length': '电话需为11位数字',
            'min_length': '电话需为11位数字',

        },
    )
    # number = forms.CharField(label='网吧代码',max_length=32)
    choice = forms.ModelChoiceField(

        queryset=cc,
        empty_label='选择地区',
        error_messages={
            'required': '地区为必选项',
            'invalid': '格式错误',
        },
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['choice'].queryset = models.City.objects.all()
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

hazhongkeji/zhizhu_proxy/views.py
from django.views import View
from django.shortcuts import render
from django.db import IntegrityError
from . import models
from .forms import Myforms


class Login(View):
    def get(self, request):
        form = Myforms()
        return render(request, 'login-forms.html', {'form': form})

    def post(self, request):
        form = Myforms(request.POST)  # 请求数据做参数
        if form.is_valid():
            wb = request.POST['wb']
            centent = {}
            username = form.cleaned_data['username']
            phone_valid = form.cleaned_data['phone']  # 推荐这么取验证后的数据
            # phone = request.POST['phone']  # 取原始数据
            city = form.cleaned_data['choice']
            try:
                wb_name = models.Wangba.objects.filter(id=wb).first()  # 不加.first()是一个可迭代的QuerySet，这里取出第一个值
            except:
                return render(request, 'error.html', )
            centent['phone_valid'] = phone_valid
            centent['city'] = city
            centent['wb'] = wb_name
            centent['username'] = username
            try:
                models.UserInfo.objects.create(username=username, phone=phone_valid, city=city, wb=wb_name)
            except IntegrityError:
                return render(request, 'error2.html', )
            return render(request, 'index.html', centent)
        else:
            error = {}
            error['form'] = form
            error['error'] = form.errors

            return render(request, 'error.html', error)



class zhizhu_index(View):
    def get(self, request):
        return render(request, 'login.html')


class Shuju(View):
    def get(self, request):
        reg = request.GET.get('country')
        obj = models.Wangba.objects.filter(wb_for_id=reg)
        return render(request, 'city_dropdown_list_options.html', {'objs': obj})

hazhongkeji/zhizhu_proxy/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" >
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.min.css' %}" >
    <link rel="stylesheet" type="text/css" href="{% static 'css/my.css' %}" >

    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />

    <title>KOC EBA2018 线上报名</title>
</head>
<body class="mybgimg">
<div class="container">
    <div class="row">
      <div class="col-sm-6 col-md-4 col-lg-3">
          <div>
              <img src="https://xiaohuaspider.oss-cn-zhangjiakou.aliyuncs.com/hongchang/bgm1.jpg" class="img-responsive center-block%">

          </div>
          {% block content %} {% endblock %}
      <br>
          {% block img_in %} {% endblock %}
      </div>
    </div>
</div>
</body>
</html>

hazhongkeji/zhizhu_proxy/templates/error.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

      <div class="mmmytop2" align="center">
          <div class="mywidth ">
              <p>{{ form.errors.username.0 }}</p>
          </div>
          <div class="mywidth">
              <p> {{ form.errors.phone.0 }}</p>
          </div>
          <div class="mywidth">
              <p>{{ form.errors.choice.0 }}</p>
          </div>
          <div class="mywidth">
              <p>网吧为必选项</p>
          </div>
          <div class="mybuttion">
              <a href="login">
                <input type="button" value="重新填写" >
              </a>
          </div>
      </div>
{% endblock %}







{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" >#}
{#    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.min.css' %}" >#}
{#    <link rel="stylesheet" type="text/css" href="{% static 'css/my.css' %}" >#}
{##}
{#    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>#}
{#    <script src="{% static 'js/bootstrap.min.js' %}"></script>#}
{##}
{#    <meta charset="UTF-8">#}
{#    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />#}
{##}
{#    <title>login-登陆</title>#}
{#</head>#}
{#<body class="mybgimg">#}
{#<div class="container">#}
{#    <div class="row">#}
{#      <div class="col-sm-6 col-md-4 col-lg-3">#}
{#          <div>#}
{#              <img src="{% static 'img/bgm.jpg' %}" alt="" height=100% width=100%>#}
{#          </div>#}
{#          <div class="mmmytop2" align="center">#}
{#              <div class="mywidth ">#}
{#                  <p>{{ form.errors.username.0 }}</p>#}
{#              </div>#}
{#              <div class="mywidth">#}
{#                  <p> {{ form.errors.phone.0 }}</p>#}
{#              </div>#}
{#              <div class="mywidth">#}
{#                  <p>{{ form.errors.choice.0 }}</p>#}
{#              </div>#}
{#              <div class="mywidth">#}
{#                  <p>网吧为必选项</p>#}
{#              </div>#}
{#              <div class="mybuttion">#}
{#                  <a href="login">#}
{#                    <input type="button" value="重新填写" >#}
{#                  </a>#}
{#              </div>#}
{#          </div>#}
{#      </div>#}
{#    </div>#}
{#</div>#}
{#</body>#}
{#</html>#}

hazhongkeji/zhizhu_proxy/templates/error2.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
      <div class="mmmytop3" align="center">
          <div class="mywidth">
              <p>您的手机号已登记，请不要重新登记</p>
          </div>
          <div class="mybuttion">
              <a href="login">
                <input type="button" value="重新填写" >
              </a>
          </div>
      </div>
{% endblock %}

hazhongkeji/zhizhu_proxy/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
      <div class="mmmytop2" align="center">
          <div class="mywidth ">
              <h1 style="color:red;">提交成功</h1>
          </div>
          <div class="mywidth">
              <p>战队队长姓名：{{ username }}</p>
          </div>
          <div class="mywidth">
              <p>联系方式：{{ phone_valid }}</p>
          </div>
          <div class="mywidth">
              <p>地区：{{ city }}</p>
          </div>
          <div class="mywidth">
              <p>网吧：{{ wb }}</p>
          </div>
          <div class="mywidth">
              <button onclick="location.href='http://www.pythonz.cn/zhizhu/login'" type="button"> 确定 </button>
          </div>
      </div>
{% endblock %}

hazhongkeji/zhizhu_proxy/templates/login-bak.html
{% load static %}

<!DOCTYPE html>
<html lang="zh_cn">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" >
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.min.css' %}" >
    <link rel="stylesheet" type="text/css" href="{% static 'css/my.css' %}" >

    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <meta charset="UTF-8">
    <title>login-登陆</title>
</head>


<body>


<div class="container-fluid">
    <div class="row">
      <div class="col-md-12 ">
          <div >
              <form method="post" class="mmmytop" name="login">
                  {% csrf_token %}
                  <div class="form-group mylogindiv">
                        <label >姓名</label>
                        <input type="text" class="form-control mylogininput" id="exampleInputName2" name="username" placeholder="姓名">
                  </div>
                  <div class="form-group mylogindiv">
                        <label >联系方式</label>
                        <input type="text" class="form-control mylogininput" id="exampleInputName2" name="phone" placeholder="联系方式">
                  </div>
                  <div class="form-group mylogindiv">
                        <label >网吧代码</label>
                        <input type="text" class="form-control mylogininput" id="exampleInputName2" name="number" placeholder="网吧代码">
                  </div>
                  <div class="btn-group mylogindiv">
                      <label >地区选择</label>
                      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Action <span class="caret"></span>
                      </button>
                      <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li><a href="#">Separated link</a></li>
                      </ul>
                  </div>
                  <div>
                      <button type="submit" class="myloginbutton mylogindiv" name="submit" > 确定登记 </button>
                  </div>
              </form>
          </div>
      </div>
    </div>
</div>


</body>

</html>

hazhongkeji/zhizhu_proxy/templates/login-forms.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
      <div>
        <form class="mmmytop" action="/zhizhu/login" method="post" novalidate="novalidate">
            {% csrf_token %}
        {#    {{ form.as_p }}#}
            <div class="mywidth">
                <label >战队队长姓名：</label>
                {{ form.username }}
                {{ form.errors.username.0 }}
            </div>
            <div class="mywidth">
                <label >联系方式：</label>
                {{ form.phone }}
                {{ form.errors.phone.0 }}
            </div>
            <div class="form-group mywidth">
                <label >地区选择：</label>
                {{ form.choice }}
                {{ form.errors.choice.0 }}
            </div>
            <div class="mywidth">
                    <label for="id_city" class="control-label">选择网吧</label>
                    <select class="form-control" id="id_city" name="wb">
                            <option  selected="selected">请选择</option>
                    </select>
                    {{ wb }}
            </div>
            <div class="mybuttion ">
                <input class="btn btn-primary" type="submit" value="提交" />
            </div>
        </form>
      </div>
<script>
    $("#id_choice").change(function () {
      var countryId = $(this).val();
      $.ajax({
        url: "/zhizhu/shuju/",
        type : "get",
        data: {
          'country': countryId
        },
        success: function (data) {
          $("#id_city").html(data);
        }

      });
    });
</script>
{% endblock %}

{% block img_in %}
    <div>
           <img src="https://xiaohuaspider.oss-cn-zhangjiakou.aliyuncs.com/hongchang/shuoming.jpg" class="img-responsive center-block%">
    </div>
    <div>
           <img src="https://xiaohuaspider.oss-cn-zhangjiakou.aliyuncs.com/hongchang/wangba1.jpg" class="img-responsive center-block%">
    </div>
    <div>
           <img src="https://xiaohuaspider.oss-cn-zhangjiakou.aliyuncs.com/hongchang/wangba2.jpg" class="img-responsive center-block%">
    </div>
    <div>
           <img src="https://xiaohuaspider.oss-cn-zhangjiakou.aliyuncs.com/hongchang/wangba3.jpg" class="img-responsive center-block%">
    </div>
    <div>
           <img src="https://xiaohuaspider.oss-cn-zhangjiakou.aliyuncs.com/hongchang/wangba4.jpg" class="img-responsive center-block%">
    </div>
    <div>
           <img src="https://xiaohuaspider.oss-cn-zhangjiakou.aliyuncs.com/hongchang/wangba6.jpg" class="img-responsive center-block%">
    </div>
{% endblock %}

hazhongkeji/zhizhu_proxy/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="zh_cn">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" >
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.min.css' %}" >
    <link rel="stylesheet" type="text/css" href="{% static 'css/my.css' %}" >

    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />

    <title>login-登陆</title>
</head>


<body>


<div class="container">
    <div class="row">
      <div class="col-sm-6 col-md-4 col-lg-3">
          <div>
              <form method="post" class="mmmytop" name="login">
                  {% csrf_token %}
                  <div class="form-group mywidth">
                        <label >姓名</label>
                        <input type="text" class="form-control " id="exampleInputName2" name="username" placeholder="姓名">
                  </div>
                  <div class="form-group mywidth">
                        <label >联系方式</label>
                        <input type="text" class="form-control " id="exampleInputName2" name="phone" placeholder="联系方式">
                  </div>
                  <div class="form-group mywidth">
                        <label >网吧代码</label>
                        <input type="text" class="form-control " id="exampleInputName2" name="number" placeholder="网吧代码">
                  </div>
                  <div class="mywidth">
                      <div>
                          <label>地区选择</label>
                      </div>
                      <div class="btn-group mywidth">
                          <button type="button" class="btn btn-default dropdown-toggle " data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                地区 <span class="caret"></span>
                          </button>
                          <ul class="dropdown-menu">
                            <li><a href="#">道理区</a></li>
                            <li><a href="#">南岗区</a></li>
                            <li><a href="#">香坊区</a></li>
                            <li><a href="#">动力区</a></li>
                          </ul>
                      </div>
                      <div class="btn-group mywidth">
                          <button type="button" class="btn btn-default dropdown-toggle " data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                网吧 <span class="caret"></span>
                          </button>
                          <ul class="dropdown-menu">
                            <li><a href="#">xx网吧1</a></li>
                            <li><a href="#">xx网吧1</a></li>
                            <li><a href="#">xx网吧1</a></li>
                            <li><a href="#">xx网吧1</a></li>
                          </ul>
                      </div>
                      <div class="mybuttion">
                          <button type="submit" name="submit" > 确定登记 </button>
                      </div>
                  </div>
              </form>
          </div>
      </div>
    </div>
</div>


</body>

</html>